### ISSUE TITLE
Peer to Peer code review:

### ISSUE THREAD

**Issue by tajulafreen** [evansnyamekye/Capstone-PR#3]

**Comment by tajulafreen** [comment]
Hi @evansnyamekye,
You had a perfect job implementing the first capstone project. Still, I will suggest one thing use semantic tags instead of `div` and `<a>` you can use `<ul>` and `<li>` tags.


✅ Thank you for distributing your project.
You did an excellent job 😄

**Comment by evansnyamekye** [comment]
Hi @tajulafreen ...Thank you for the review. 😀 👍
